version: "3.2"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200525
    hostname: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - dev
  chrome:
    image: selenium/node-chrome-debug:3.141.59-20200525
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    ports:
      - "5555:5555"
      - "5900:5900"
    networks:
      - dev
  tomcat:
    image: tomcat:9.0
    hostname: tomcat-server
    ports:
      - "8181:8080"
    volumes:
      - "../testapp/target/testapp.war:/usr/local/tomcat/webapps/testapp.war"
    networks:
      - dev
  backend:
    image: tomcat:9.0
    hostname: backend-server
    ports:
      - "8282:8080"
    volumes:
      - "../testapp/target/testapp.war:/usr/local/tomcat/webapps/testapp.war"
    networks:
      - dev
  #  jenkins:
  #    build: ./jenkins
  #    hostname: jenkins-server
  #    ports:
  #      - "18080:8080"
  #      - "50000:50000"
  #    volumes:
  #      - "./jenkins/jenkins_home:/var/jenkins_home"
  #    networks:
  #      - dev
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    networks:
      - dev
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
networks:
  dev: