version: "3.2"
services:
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4442-4444"
    networks:
      - dev
    environment:
      - JAVA_OPTS=-Xms2g -Xmx8g
  chrome:
    image: selenium/node-chrome:4.15.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_MAX_INSTANCES=5
#      - SE_NODE_MAX_SESSIONS=5
    ports:
#      - "5555"
      - "5900:5900"
    networks:
      - dev
  tomcat:
    image: tomcat:9.0
    ports:
      - "8080"
    volumes:
      - "../testapp/target/testapp-LOCALBUILD-SNAPSHOT.war:/usr/local/tomcat/webapps/testapp.war"
    networks:
      - dev
  #  jenkins:
  #    build: ./jenkins
  #    hostname: jenkins-server
  #    ports:
  #      - "18080:8080"
  #      - "50000:50000"
  #    volumes:
  #      - "./jenkins/jenkins_home:/var/jenkins_home"
  #    networks:
  #      - dev
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    networks:
      - dev
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
networks:
  dev: